### ISSUE TITLE
Can you help edit the database credentials for mysql?

### ISSUE THREAD

**Issue by jigsaw007** [bolinocroustibat/import-gsheet-to-sql#1]
It looks like its for sqllite, But I would like to do it for mysql. 

Also where do I enter the google sheet url or ID in import_sheet.php?

**Comment by bolinocroustibat** [comment]
It works also for MySQL. Just edit the connection script for your MySQL DB credentials (like `$db = new PDO('mysql:host=localhost;port=3306;dbname=dbname', 'mysqluser', 'mysqlpassword');`)

Google Sheet URL must be passed as an argument of the PHP command like in the README file.
